# Generated by Django 5.2.4 on 2025-07-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=10)),
                ('region', models.CharField(choices=[('IN', 'India'), ('US', 'USA')], default='IN', max_length=10)),
                ('persona', models.CharField(choices=[('genz', 'Gen Z'), ('elderly', 'Elderly'), ('minority', 'Minority Group')], default='genz', max_length=10)),
            ],
        ),
    ]
