# Generated by Django 5.2.4 on 2025-07-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_quizquestion_remove_userchallengeattempt_challenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='correct_answers',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
